### ISSUE TITLE
readme doesnt render on pypi

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-manage/manage#15]

**Comment by RodolfoFerro** [comment]
As mentioned in https://stackoverflow.com/questions/17401132/restructuredtext-readme-rst-not-parsing-on-pypi, you might be using a different version of support docutils.

**Comment by RonnyPfannschmidt** [comment]
my version of docutils is not relevant to pypi at all ^^

**Comment by jorgeecardona** [comment]
Duplicate of #10
