### ISSUE TITLE
A DeprecationWarning of PyYAML is shown every time the CLI is used.

### ISSUE THREAD

**Issue by jorgeecardona** [python-manage/manage#18]
* Manage version: 0.1.13
* Python version: python 3.7.3
* Operating System: Debian (unstable)

### Description

The package PyYAML is deprecating the usage of `yaml.load` without passing explicitly the `Loader` and a deprecationg message is shown every time I use the manage CLI:

```
../site-packages/manage/cli.py:44: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  MANAGE_DICT.update(yaml.load(manage_file))
```

**Comment by kersommoura** [comment]
This issue was closed by the https://github.com/python-manage/manage/pull/17
